-- require('dashboard').setup({
--     theme = 'doom', --  theme is doom and hyper default is hyper
-- disable_move,    --  defualt is false disable move keymap for hyper
-- shortcut_type,   --  shorcut type 'letter' or 'number'
-- change_to_vcs_root, -- default is false,for open file in hyper mru. it will change to the root of vcs
-- config = {},    --  config used for theme
-- })
-- 
-- 
